### ISSUE TITLE
issues:"pyqtdeploy-sysroot: PyQt: SIP v5 is required."

### ISSUE THREAD

**Issue by lzlxm** [PJ-Finlay/pyqtdeploy#1]
Hello!
    I run build-demo.py and  it report "pyqtdeploy-sysroot: PyQt: SIP v5 is required.".
   full information is next:
Verifying host architecture 'win-64'...
Verifying target architecture 'win-64'...
Verifying Python v3.7.8...
Verifying PyQt v5.15.2...
pyqtdeploy-sysroot: PyQt: SIP v5 is required.

and my related modules version:
 ISP:6.0.1
PyQt-bulider:1.8.0
PyQt5-sip:12.8.1
PyQt5:5.15.2
pyqtdeploy:3.1.1

Why did it report this, can you help me?Thank you!

Best regards!

**Comment by PJ-Finlay** [comment]
I think you need to install an older version of SIP. Did you install from `demo/requirements.txt` using `demo/setup.sh`? It's possible that they have the wrong version number.


- [pyqtdeploy-sysroot fails with SIP 6.0.0](http://python.6.x6.nabble.com/pyqtdeploy-sysroot-fails-with-SIP-6-0-0-td5285972.html)

**Comment by lzlxm** [comment]
Hi!

&nbsp;&nbsp;&nbsp; Thank you for your reply! I&nbsp;will&nbsp;try to do from&nbsp;the link&nbsp;"pyqtdeploy-sysroot fails with SIP 6.0.0".

&nbsp;&nbsp;&nbsp;&nbsp; If I success, I will reply the email&nbsp;again.Many thanks.

&nbsp;&nbsp;&nbsp;&nbsp; Best Regard!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PJ-Finlay/pyqtdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PJ-Finlay/pyqtdeploy] issues:"pyqtdeploy-sysroot: PyQt: SIP v5 is required." (#1)





 
I think you need to install an older version of SIP. Did you install from demo/requirements.txt using demo/setup.sh? It's possible that they have the wrong version number.
  
pyqtdeploy-sysroot fails with SIP 6.0.0
